import { test, expect } from "@playwright/test";
import { openFixture } from "./helpers.mjs";
const frames = Array.from({length:3}, (_,i)=>({id:"frame-"+i,number:i+1,shot:"WS",lens:"35mm",angle:"None",beat:"Original beat",prompt:"Original prompt "+i,notes:"",resultUrl:"/outputs/e2e/original-"+i+".png",status:"complete"}));
async function setup(page, planIsCurrent = false, count = 1) {
  await page.addInitScript(({ frames, planIsCurrent }) => { if (!sessionStorage.getItem("seedance-node-editor-draft-v1")) sessionStorage.setItem("seedance-node-editor-draft-v1", JSON.stringify({nodes:[{id:"board",type:"storyboard",x:10,y:10,data:{title:"Board",storyboardTab:"view",sceneDescription:"A bottle on a table",storyboardPlanSceneDescription:planIsCurrent ? "A bottle on a table" : "Old scene deliberately changed",storyboardFrames:frames,storyboardAutoQc:false,useInternalStoryboardCharacters:false}}],edges:[],groups:[],viewport:{x:0,y:0,scale:0.7}})); },{ frames, planIsCurrent });
  const fixture=await openFixture(page,{count,settings:{falKeyConfigured:true,modelProviderPreferences:{imageGeneration:"fal",llm:"fal"}}});
  return { ...fixture, card:page.locator('[data-node-card-id="board"]') };
}
const savedFrames = page => page.evaluate(()=>JSON.parse(sessionStorage.getItem("seedance-node-editor-draft-v1")).nodes[0].data.storyboardFrames);
test("selected revisions commit successful replacements and preserve failed and unselected panels", async ({page}, testInfo) => {
  const {card,errors}=await setup(page);let plans=[],images=[];
  await page.route("**/api/node/storyboard-revise",async route=>{const b=route.request().postDataJSON();plans.push(b);await route.fulfill({json:{revision:{frames:b.frames.filter(f=>b.frameIds.includes(f.id)).map(({id,number})=>({id,number,shot:"CU",lens:"85mm",angle:"None",beat:"New beat",prompt:"Revised prompt "+number,notes:"Keep bottle"})),warnings:[]}}});});
  await page.route("**/api/node/generate-image",async route=>{images.push(route.request().postDataJSON());await route.fulfill(images.length===2?{status:502,json:{error:"Mock provider failed"}}:{json:{images:[{localUrl:"/outputs/e2e/revised.png",mimeType:"image/png"}]}});});
  await page.route("**/api/node/storyboard-export-frame",route=>route.fulfill({json:{frame:{localUrl:"/outputs/e2e/revised-export.png",fileName:"revised.png"}}}));
  await card.getByLabel("Select panel 1 for revision").check();await card.getByLabel("Select panel 2 for revision").check();
  await card.getByLabel("Selected panel revision").fill("Move closer, preserve the bottle");
  await card.getByRole("button",{name:"Revise Selected",exact:true}).click();
  await expect(card.getByRole("button",{name:"Revise Selected",exact:true})).toBeEnabled();
  await expect.poll(()=>images.length).toBe(2);
  await expect.poll(async()=> (await savedFrames(page))[0].prompt).toBe("Revised prompt 1");
  const saved=await savedFrames(page);
  expect(saved[0].shot).toBe("CU");expect(saved[0].resultUrl).toBe("/outputs/e2e/revised.png");
  expect(saved[1].prompt).toBe(frames[1].prompt);expect(saved[1].resultUrl).toBe(frames[1].resultUrl);expect(saved[1].error).toContain("Mock provider failed");
  expect(saved[2].prompt).toBe(frames[2].prompt);expect(saved[2].resultUrl).toBe(frames[2].resultUrl);
  expect(plans).toHaveLength(1);expect(plans[0].frames).toHaveLength(3);expect(plans[0].frameIds).toEqual(["frame-0","frame-1"]);
  expect(images[0].storyboardRevision).toBe(true);expect(images[0].imagePromptUrls).toContain(frames[0].resultUrl);
  await page.screenshot({path:testInfo.outputPath("revisions.png")});
  await page.reload();await page.getByRole("button",{name:"Nodes",exact:true}).click();
  await expect(card.getByLabel("Selected panel revision")).toHaveValue("Move closer, preserve the bottle");
  expect((await savedFrames(page))[1].resultUrl).toBe(frames[1].resultUrl);expect(errors).toEqual([]);
});
test("failed revision planning leaves every panel unchanged and submits no images",async({page})=>{
  const {card,errors}=await setup(page);let images=0;
  await page.route("**/api/node/storyboard-revise",route=>route.fulfill({status:400,json:{error:"Revision returned invalid panels"}}));
  await page.route("**/api/node/generate-image",route=>{images++;return route.abort();});
  await card.getByLabel("Select panel 2 for revision").check();await card.getByLabel("Selected panel revision").fill("Closer");await card.getByRole("button",{name:"Revise Selected",exact:true}).click();
  await expect(card.getByText("Revision returned invalid panels",{exact:true})).toBeVisible();
  expect(images).toBe(0);expect((await savedFrames(page)).map(f=>f.resultUrl)).toEqual(frames.map(f=>f.resultUrl));expect(errors).toEqual([]);
});

test("panel protection blocks editing, replanning and generation; restoring a version preserves the displaced image", async ({page},testInfo) => {
 const {card,errors}=await setup(page,true); let plans=0, images=0;
 await page.route("**/api/node/storyboard-plan",r=>{plans++;return r.abort();});
 await page.route("**/api/node/generate-image",r=>{images++;return r.fulfill({json:{images:[{localUrl:"/outputs/e2e/new-"+images+".png",mimeType:"image/png"}]}});});
 await page.route("**/api/node/storyboard-export-frame",r=>r.fulfill({json:{frame:{localUrl:r.request().postDataJSON().sourceUrl,fileName:"new.png"}}}));
 const panel=card.locator('[data-storyboard-frame-id="frame-0"]').first();
 await panel.getByRole("button",{name:"Protect panel",exact:true}).click();
 await expect(panel.getByRole("button",{name:"Run",exact:true})).toBeDisabled();
 await expect(panel.getByLabel("Select panel 1 for revision")).toBeDisabled();
 await expect(panel.locator("select").first()).toBeDisabled();
 await card.getByRole("button",{name:"Plan",exact:true}).click();
 await expect(card.getByText("Unprotect panels before replacing the storyboard plan.",{exact:true})).toBeVisible();expect(plans).toBe(0);
 await card.getByRole("button",{name:"Generate",exact:true}).click();
 await expect.poll(()=>images).toBe(2);
 await expect.poll(async()=> (await savedFrames(page))[1].versions?.length).toBe(1);
 expect((await savedFrames(page))[0].resultUrl).toBe(frames[0].resultUrl);
 const second=card.locator('[data-storyboard-frame-id="frame-1"]').first();
 await second.getByText("Previous versions (1)",{exact:true}).click();
 await second.getByRole("button",{name:"Protect panel",exact:true}).click();
 await expect(second.getByRole("button",{name:"Restore panel 2 version 1"})).toBeDisabled();
 await second.getByRole("button",{name:"Unprotect panel",exact:true}).click();
 await second.getByRole("button",{name:"Restore panel 2 version 1"}).click();
 await expect.poll(async()=> (await savedFrames(page))[1].resultUrl).toBe(frames[1].resultUrl);
 expect((await savedFrames(page))[1].versions.at(-1).resultUrl).toBe("/outputs/e2e/new-1.png");
 await page.screenshot({path:testInfo.outputPath("panel-history.png")});
 await page.reload();await page.getByRole("button",{name:"Nodes",exact:true}).click();
 await expect(panel.getByRole("button",{name:"Unprotect panel",exact:true})).toBeVisible();
 expect((await savedFrames(page))[1].versions).toHaveLength(1);expect(errors).toEqual([]);
});

test("spatial plans reach generation and review, survive reload, and clear after manual camera edits",async({page})=>{
 await page.addInitScript(()=>{if (sessionStorage.getItem("seedance-node-editor-draft-v1")) return; sessionStorage.setItem("seedance-node-editor-draft-v1",JSON.stringify({nodes:[{id:"board",type:"storyboard",x:10,y:10,data:{title:"Board",sceneDescription:"Two people talk across a table",useInternalStoryboardCharacters:false,storyboardAutoQc:true,storyboardTab:"setup"}}],edges:[],groups:[],viewport:{x:0,y:0,scale:0.7}}));});
 const {card,errors}=await setup(page);let imageRequest,reviewRequest;
 const spatial={spaceId:"cafe",cameraSetupId:"master",view:"Both seats and table",visiblePlaces:["west-seat","east-seat"],present:[{tag:"Alice",place:"west-seat"},{tag:"Bob",place:"east-seat"}],hidden:[],blockingChange:""};
 const cast=spatial.present.map(p=>({tag:p.tag,visibility:"visible",position:p.place,action:"Talking",eyeline:"Across table"}));
 await page.route("**/api/node/storyboard-plan",r=>r.fulfill({json:{plan:{sceneTitle:"Cafe",analysis:"Both seats stay visible",frames:[{number:1,shot:"MS",lens:"35mm",angle:"None",prompt:"Two people seated across a table",beat:"They talk",notes:"",spatial,cast}]}}}));
 await page.route("**/api/node/generate-image",r=>{imageRequest=r.request().postDataJSON();return r.fulfill({json:{images:[{localUrl:"/outputs/e2e/spatial.png",mimeType:"image/png"}]}});});
 await page.route("**/api/node/storyboard-qc",r=>{reviewRequest=r.request().postDataJSON();return r.fulfill({json:{qc:{pass:true,severity:"ok",summary:"Both seated",issues:[],shouldRetry:false,correctionPrompt:""}}});});
 await page.route("**/api/node/storyboard-export-frame",r=>r.fulfill({json:{frame:{localUrl:"/outputs/e2e/spatial.png",fileName:"spatial.png"}}}));
 await card.getByRole("button",{name:"Plan",exact:true}).click();
 await expect(card.locator(".storyboard-frame-card")).toHaveCount(1);
 await card.getByRole("button",{name:"Generate",exact:true}).click();
 await expect.poll(()=>reviewRequest?.framePrompt || "").toContain("Bob at east-seat");
 expect(imageRequest.prompt).toContain("PHYSICAL STAGING");
 await expect.poll(async()=>(await savedFrames(page))?.[0]?.resultUrl).toBe("/outputs/e2e/spatial.png");
 expect((await savedFrames(page))[0].spatial).toEqual(spatial);
 await page.reload();await page.getByRole("button",{name:"Nodes",exact:true}).click();
 expect((await savedFrames(page))[0].spatial).toEqual(spatial);
 await card.locator(".storyboard-frame-controls select").first().selectOption("CU");
 await expect.poll(async()=>(await savedFrames(page))[0].spatial).toBeNull();
 expect((await savedFrames(page))[0].generatedDirection.spatial).toEqual(spatial);
 expect(errors).toEqual([]);
});

 test("sequence review is advisory and quality mode persists",async({page},testInfo)=>{
 const {card,errors}=await setup(page,true);let reviews=0,images=0;
 await page.route("**/api/node/storyboard-review",r=>{reviews++;return r.fulfill({json:{review:{summary:"Sequence reads clearly",directionsOnly:true,issues:[{frameIds:["frame-1"],message:"Consider a closer reaction"}]}}});});
 await page.route("**/api/node/generate-image",r=>{images++;return r.abort();});
 await card.getByRole("button",{name:"Review Sequence",exact:true}).click();
 await expect(card.getByText("Sequence reads clearly",{exact:true})).toBeVisible();
 await expect(card.getByText("Panels 2: Consider a closer reaction",{exact:true})).toBeVisible();
 expect(reviews).toBe(1);expect(images).toBe(0);expect((await savedFrames(page)).map(f=>f.resultUrl)).toEqual(frames.map(f=>f.resultUrl));
 await card.getByText("Advanced",{exact:true}).click();
 await expect(card.getByLabel("Storyboard quality control")).toHaveValue("off");
 await card.getByLabel("Storyboard quality control").selectOption("deep");
 await expect.poll(()=>page.evaluate(()=>JSON.parse(sessionStorage.getItem("seedance-node-editor-draft-v1")).nodes[0].data.storyboardQcMode)).toBe("deep");
 await page.screenshot({path:testInfo.outputPath("quality-control.png")});
 await page.reload();await page.getByRole("button",{name:"Nodes",exact:true}).click();
 await expect(card.getByLabel("Storyboard quality control")).toHaveValue("deep");
 await card.getByRole("tab",{name:"Storyboard View",exact:true}).click();
 await expect(card.getByText("Sequence reads clearly",{exact:true})).toBeVisible();
 await page.screenshot({path:testInfo.outputPath("sequence-review.png")});
 const qcRequests=[];
 await page.route("**/api/node/storyboard-qc",r=>{qcRequests.push(r.request().postDataJSON());return r.fulfill({json:{qc:{pass:true,severity:"ok",summary:"Fine",shouldRetry:false,issues:[],correctionPrompt:""}}});});
 await page.route("**/api/node/generate-image",r=>r.fulfill({json:{images:[{localUrl:"/outputs/e2e/new.png",mimeType:"image/png"}]}}));
 await page.route("**/api/node/storyboard-export-frame",r=>r.fulfill({json:{frame:{localUrl:r.request().postDataJSON().sourceUrl,fileName:"new.png"}}}));
 await card.locator('[data-storyboard-frame-id="frame-0"]').first().getByRole("button",{name:"Run",exact:true}).click();
 await expect.poll(()=>qcRequests.length).toBe(1);expect(qcRequests[0].qcMode).toBe("deep");
 await expect(card.getByRole("button",{name:"Review Sequence",exact:true})).toBeEnabled();
 await card.getByText("Advanced",{exact:true}).click();await card.getByLabel("Storyboard quality control").selectOption("off");
 await card.getByRole("tab",{name:"Storyboard View",exact:true}).click();
 await card.locator('[data-storyboard-frame-id="frame-1"]').first().getByRole("button",{name:"Run",exact:true}).click();
 await expect.poll(async()=> (await savedFrames(page))[1].resultUrl).toBe("/outputs/e2e/new.png");expect(qcRequests).toHaveLength(1);
 expect(errors).toEqual([]);
 });

test("board assembles automatically, retries failures, rejects stale uploads and exports directly",async({page},testInfo)=>{
 await page.addInitScript(frames=>{if(!sessionStorage.getItem("seedance-node-editor-draft-v1")) sessionStorage.setItem("seedance-node-editor-draft-v1",JSON.stringify({nodes:[{id:"board",type:"storyboard",x:10,y:10,data:{title:"Board",storyboardTab:"view",sceneDescription:"A bottle on a table",storyboardPlanSceneDescription:"A bottle on a table",storyboardFrames:frames,storyboardAutoQc:false,useInternalStoryboardCharacters:false}},{id:"preview-board",type:"preview",x:1000,y:10,data:{title:"Board Preview"}}],edges:[{id:"board-preview",from:{nodeId:"board",port:"storyboardOut"},to:{nodeId:"preview-board",port:"sourceIn"}}],groups:[],viewport:{x:0,y:0,scale:0.7}}));},frames);
 const {card,errors}=await setup(page,true,2);let uploads=0;let release;
 await page.route("**/api/node/storyboard-export-frame",r=>r.fulfill({json:{frame:{localUrl:r.request().postDataJSON().sourceUrl,fileName:"generated.png"}}}));
 await page.route("**/api/node/upload-asset",async r=>{uploads++;if(uploads===1)return r.fulfill({status:500,json:{error:"Mock disk full"}});if(uploads===2){await new Promise(resolve=>release=resolve);return r.fulfill({json:{asset:{localUrl:"/outputs/e2e/stale-board.png",fileName:"stale.png",mimeType:"image/png"}}});}return r.fulfill({json:{asset:{localUrl:"/outputs/e2e/current-board.png",fileName:"board.png",mimeType:"image/png"}}});});
 await expect(card.getByRole("button",{name:"Export Frames",exact:true})).toBeVisible();await expect(card.getByRole("button",{name:"Export PDF",exact:true})).toBeVisible();
 await expect(card.getByRole("button",{name:"Retry board assembly"})).toBeVisible();expect(uploads).toBe(1);
 await card.getByRole("button",{name:"Retry board assembly"}).click();await expect.poll(()=>uploads).toBe(2);
 await card.getByRole("button",{name:"Add frame",exact:true}).click();
 await card.locator('[data-storyboard-frame-id="frame-0"]').first().getByRole("button",{name:"Run",exact:true}).click();
 await expect(card.getByRole("button",{name:"Export PDF",exact:true})).toBeEnabled();
 // A new source version must supersede an already-uploading sheet.
 release();
 await expect.poll(()=>page.evaluate(()=>JSON.parse(sessionStorage.getItem("seedance-node-editor-draft-v1")).nodes[0].data.storyboardBoardUrl)).toBe("/outputs/e2e/current-board.png");
 await expect(page.locator('[data-node-card-id="preview-board"] img').first()).toHaveAttribute("src", /current-board/);
 const exported=[];
 await page.route("**/api/system/select-save-path",r=>r.fulfill({json:{path:r.request().postDataJSON().extension==="pdf"?"C:/exports/board.pdf":"C:/exports/frames"}}));
 await page.route("**/api/node/storyboard-export-board",r=>{exported.push(r.request().postDataJSON());return r.fulfill({json:{export:{frameCount:3,folderPath:"C:/exports",frames:[],pdf:null}}});});
 await card.getByRole("button",{name:"Export Frames",exact:true}).click();await expect.poll(()=>exported.length).toBe(1);
 await card.getByRole("button",{name:"Export PDF",exact:true}).click();await expect.poll(()=>exported.length).toBe(2);
 expect(exported[0].includeFrames).toBe(true);expect(exported[1].includePdf).toBe(true);expect(exported[1].generateDescriptions).toBe(false);expect(exported[1].frames.map(f=>f.number)).toEqual([1,2,3]);
 await page.screenshot({path:testInfo.outputPath("automatic-board.png")});
 await page.reload();await page.getByRole("button",{name:"Nodes",exact:true}).click();
 await expect(card.getByRole("button",{name:"Export PDF",exact:true})).toBeVisible();expect(errors).toEqual([]);
});
